# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

spark.sql("USE CATALOG `openaq`")
spark.sql("USE SCHEMA `livestreamdata`")

# COMMAND ----------

dbutils.fs.ls("/Volumes/openaq/livestreamdata/raw_data/openaq_v3/")

# COMMAND ----------

dbutils.fs.ls("/Volumes/openaq/livestreamdata/raw_data/openaq_v3/san_francisco/")

# COMMAND ----------

from pyspark.sql import functions as F

# Lectura de JSONs multilinea
raw_df = spark.read.option("multiline", "true") \
    .json("/Volumes/openaq/livestreamdata/raw_data/openaq_v3/*/*.json")


explorer_df = raw_df.select(
    F.col("_metadata.file_path").alias("source_path"),
    F.explode("results").alias("r")
).select(
    F.regexp_extract("source_path", r"openaq_v3/([^/]+)", 1).alias("city"),
    F.col("r.parameter.name").alias("parameter"),
    F.col("r.parameter.units").alias("units"), 
    F.col("r.value").alias("value"),
    F.col("r.period.datetimeTo.utc").alias("utc_date") 
)

display(explorer_df)
